### ISSUE TITLE
GTA SA Game crashes Unhandled Exception

### ISSUE THREAD

**Issue by BolloEG** [JuniorDjjr/CLEOPlus#12]
Hello again my friend! and sorry for the late answer, it took me a lot of time to discover this.

https://www.youtube.com/watch?v=kfdSM6fRujk

The first person mod (just used 3.0 version with BoPoH's logo so you can see that's the mod) crashes with the log 0x006D1080 

According to crashlist it's related to a Failure to handle a vehicle.  Please I beg you to fix it if possible

**I strongly believe this mod is also causing the ultra random ntdll.dll crash. But I still don't have enought evidence.** 

Game version: GTA SA 1.0 US
Unhandled exception at 0x006D1080 in gta_sa.exe (+0x2d1080): 0xC0000005: Access violation reading location 0x00000384.
        
    Backtrace (may be wrong):
        =>0x006D1080 in gta_sa.exe (+0x2d1080) (0x0028F5F0) 
          0x74CA19FE in FirstPerson.sp (+0x19fe) (0x0028F600) 
          0x74E2113E in Hooks.asi (+0x113e) 

And here is the log for the ntdll.dll crash 

Game version: GTA SA 1.0 US
Unhandled exception at 0x77DFF017 in ntdll.dll (+0x3f017): 0xC0000005: Access violation writing location 0x00000014.
        
    Backtrace (may be wrong):
        =>0x77DFF017 LdrFindResource_U+0x184 in ntdll.dll (+0x3f017) (0x0727FF28) 
          0x77DFEF26 LdrFindResource_U+0x93 in ntdll.dll (+0x3ef26) (0x0727FF50) 
          0x1100A3AC in BASS.dll (+0xa3ac) (0x0727FF58) 
          0x1100E065 BASS_Update+0xe7 in BASS.dll (+0xe065) (0x0727FF6C) 
          0x1102106E BASS_Init+0xa41 in BASS.dll (+0x2106e)

**Comment by BolloEG** [comment]
Also tested 3.0 from mixmods with latest Cleo 4.4.4 in vanilla game without any mod

**Comment by JuniorDjjr** [comment]
Why you issued as CLEO+?
`0x006D1080` is `CVehicle::GetVehicleAppearance` that is called directly from `FirstPerson.sp (+0x19fe)`, nothing related to CLEO+.

**Comment by BolloEG** [comment]
So sorry, as mixmods is stopped since a long time, this is the only way I know to reach you. But don't worry, I won't be posting again here as cleo and cleo+ seem to be very polished at this point. Please I beg you to fix FP.
