### ISSUE TITLE
0E4D: Random_Percent Favors True

### ISSUE THREAD

**Issue by OrionSR** [JuniorDjjr/CLEOPlus#13]
I was researching Random_Percent for the Sanny Builder Library documentation and noticed that it slightly favored True.
Another test returned True approximately 1% of the time with a percentage of 0.

Changing the random number generation min and max values to 1 and 101 should provide more accurate results.

**Comment by JuniorDjjr** [comment]
Ah yes, because I used `<=` instead of `<` so `0 == 0`

**Comment by OrionSR** [comment]
I have trouble following the C coding but I'm pretty sure the `<=` operator is correct. It's just that the integers generated shouldn't include 0, and should include 100, so an RNG range of 1 to 101 is appropriate for this task.

**Comment by x87** [comment]
I think if we change the sign to `<` AND keep the range 0 to 100 it should produce the correct result.

**Comment by x87** [comment]
with `<=` the correct range is 1 to 101

**Comment by OrionSR** [comment]
Yeah, you're right. There's more than one way to code this correctly.

**Comment by JuniorDjjr** [comment]
Yes, two solutions for the same problem. I'm going to release a big CLEO+ update soon (just testing yet) and this fix will be included.
