### ISSUE TITLE
 Memory Error 0x7364de70 pops up after installing cleo+ 

### ISSUE THREAD

**Issue by Octavio1994** [JuniorDjjr/CLEOPlus#5]
First of all I just want to thank you for helping so much the GTA SA community :)

I get this error everytime I install cleo+ on my game 

I have: No modded GTA SA V1.0 USA running on windows 7
            latest cleo version installed
            latest modloader version installed 
            exdisp.asi to extend display 

When I start the game with the CLEO+ script it goes smoth and fine, but after adding any additional cleo script the game shows this error after exiting the game, sometimes it freezes my desk and have to force detention

the instruction at 0x7364de70 referenced memory at 0x7364de70 the memory could not be read

This does not happen if I remove the CLEO+ script from the folder.

**Comment by JuniorDjjr** [comment]
This is not a valid static memory address, this says nothing.

Use [CrashInfo](https://www.mixmods.com.br/2022/09/crashinfo/) to get better informations.
Use [SCRLog](https://www.mixmods.com.br/2020/10/iii-vc-sa-scrlog-2020-3-descobrir-crash-em-mod-cleo/) to know which script causes this.

"sometimes it freezes my desk and have to force detention"
https://www.mixmods.com.br/2019/06/sa-essentials-pack/ to improve how the game runs and fixes window issues (includes CrashInfo too)

**Comment by Octavio1994** [comment]
Hi back! I installed both mods but it seems they don't show any crash log... CrashInfo where the exe is and SCRLog to the Modloader folder.    So I recorded this video to show you the issue

https://www.youtube.com/watch?v=7A8Vdtf97r0

When installing cleo+ and any other cleo script the memory error pops up! 

The error does not appear if: only have cleo+ script is in the cleo folder  or
                                                 The cleo+ script is erased from the cleo folder 

this is the log from SCR but it seems useless... 


********************************************
 script oddveh
 Local variables dump:
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 4666 4666
********************************************

Finished processing.

********************************************
 script main
 Local variables dump:
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 5852 5852
********************************************

00060055&0: [00D6] IF 0
00060059&0: [0256] IS_PLAYER_PLAYING 0    // TRUE
00060064&1: [004D] GOTO_IF_FALSE 61784
00060071&1: [077E] GET_AREA_VISIBLE -> 0
00060076&1: [0652] GET_INT_STAT 181 -> 0
00060084&1: [07D0] GET_CURRENT_DAY_OF_WEEK -> 4
00060089&1: [09FB] GET_CURRENT_LANGUAGE -> 0
00060094&1: [0842] GET_CITY_PLAYER_IS_IN 0 -> 1
00060102&1: [01BD] GET_GAME_TIMER -> 5331
00060107&1: [00D6] IF 0
00060111&0: [0038] g672(0) == 1    // FALSE
00060118&0: [004D] GOTO_IF_FALSE 60190
00060190&0: [00D6] IF 24
00060194&0: [03B0] IS_GARAGE_OPEN "BODLAWN"    // FALSE
00060205&0: [03B0] IS_GARAGE_OPEN "MODLAST"    // FALSE
00060216&0: [03B0] IS_GARAGE_OPEN "MDSSFSE"    // FALSE
00060227&0: [03B0] IS_GARAGE_OPEN "MDS1SFS"    // FALSE
00060238&0: [03B0] IS_GARAGE_OPEN "VECMOD"    // FALSE
00060249&0: [004D] GOTO_IF_FALSE 60312
00060312&0: [090F] COMMAND_090F 66
00060316&0: [00D6] IF 0
00060320&0: [0491] HAS_CHAR_GOT_WEAPON 1 46    // FALSE
00060327&0: [004D] GOTO_IF_FALSE 60390
00060390&0: [090F] COMMAND_090F 0
00060394&0: [00D6] IF 1
00060398&1: [0491] HAS_CHAR_GOT_WEAPON 1 43    // FALSE
00060405&0: [0038] g409(1) == 0    // FALSE
00060412&0: [004D] GOTO_IF_FALSE 60475
00060475&0: [090F] COMMAND_090F 75
00060479&0: [00D6] IF 0
00060483&0: [0038] g409(1) == 0    // FALSE
00060490&0: [004D] GOTO_IF_FALSE 61471
00061471&0: [00D6] IF 21
00061475&0: [0038] g417(0) == 1    // FALSE
00061482&0: [0038] g418(0) == 1    // FALSE
00061489&0: [004D] GOTO_IF_FALSE 61503
00061503&0: [0004] g708(-1) = -1
00061510&0: [00D6] IF 0
00061514&0: [0256] IS_PLAYER_PLAYING 0    // TRUE
00061519&1: [004D] GOTO_IF_FALSE 61784
00061526&1: [00D6] IF 0
00061530&0: [00A3] IS_CHAR_IN_AREA_2D 1 2037.54 2365.37 2117.18 2483.92 0    // FALSE
00061557&0: [004D] GOTO_IF_FALSE 61620
00061620&0: [090F] COMMAND_090F 70
00061624&0: [00D6] IF 0
00061628&0: [04A3] g1866(1) == 1    // TRUE
00061635&1: [004D] GOTO_IF_FALSE 61784
00061642&1: [00D6] IF 0
00061646&0: [00FE] LOCATE_CHAR_ANY_MEANS_3D 1 658.007 -1866.31 4.4537 15.0 15.0 15.0 0    // FALSE
00061683&0: [004D] GOTO_IF_FALSE 61759
00061759&0: [00D6] IF 0
00061763&0: [0038] g157(0) == 1    // FALSE
00061770&0: [004D] GOTO_IF_FALSE 61784
00061784&0: [0002] GOTO 60051
00060051&0: [0001] WAIT 0
Finished processing.

********************************************
 script weadrop
 Local variables dump:
 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 5852 5852
********************************************

00000058&0: [00D6] IF 0
00000062&0: [0256] IS_PLAYER_PLAYING 0    // TRUE
00000067&1: [004D] GOTO_IF_FALSE -54
00000074&1: [00D6] IF 4
00000078&1: [03EE] CAN_PLAYER_START_MISSION 0    // TRUE
00000083&1: [80DF] NOT IS_CHAR_IN_ANY_CAR 1    // TRUE
00000088&1: [8818] NOT IS_CHAR_IN_AIR 1    // TRUE
00000093&1: [82D8] NOT IS_CURRENT_CHAR_WEAPON 1 0    // FALSE
00000100&0: [82D8] NOT IS_CURRENT_CHAR_WEAPON 1 40    // TRUE
00000107&0: [004D] GOTO_IF_FALSE -151
00000151&0: [00D6] IF 0
00000155&0: [8039] NOT l6(0) == 0    // FALSE
00000166&0: [004D] GOTO_IF_FALSE -221
00000221&0: [00D6] IF 1
00000225&1: [0039] l6(0) == 0    // TRUE
00000236&1: [8039] NOT l7(0) == 0    // FALSE
00000247&0: [004D] GOTO_IF_FALSE -288
00000288&0: [000A] l0(4) += 1
00000295&0: [00D6] IF 0
00000299&0: [0019] l0(5) > 9    // FALSE
00000306&0: [004D] GOTO_IF_FALSE -54
00000054&0: [0001] WAIT 0
Finished processing.

*********************************
> Logging finished: 15:01:10
  Powered by SCRLog (by LINK/2012)
  GTA:VC JP support by lazyuselessman
  Improvements by Junior_Djjr
*********************************

**Comment by Octavio1994** [comment]
I recorded a second video, in this one I delete the cleo+ script leaving one script (weapon drop n save) and the memory error does not appear

https://www.youtube.com/watch?v=XibSgituHCQ&t=18s

**Comment by JuniorDjjr** [comment]
So find it manually and tell here.

**Comment by JuniorDjjr** [comment]
So find it manually and tell here.

**Comment by Octavio1994** [comment]
Hello back my friend and sorry for the late answer!

after checking in other computers, I realized the bug was caused because of an unoficial modloader version that I installed from gamemodding thinking it would improve my game performance

https://gamemodding.com/es/gta-san-andreas/others/74920-mod-loader-038.html

I apologize for the inconvenient, please close this thread and continue with that great work you have made so far :)

**Comment by Octavio1994** [comment]
PLEASE don't close thread yet, I'm having a BIG issue with attach vehicle script, when I attach a car to any custom helicopter 

https://www.gtaall.net/gta-san-andreas/helicopters/59708-ch-47-chinook.html

https://www.gtaall.com/gta-san-andreas/helicopters/24142-ch-53.html

The attached vehicle flies away from the heli without any reason and sometimes the game even crashes

**Comment by JuniorDjjr** [comment]
Send log

**Comment by Octavio1994** [comment]
So sorry again, completely fixed after reinstalling cleo libraries, pls close thread
