### ISSUE TITLE
Game crashes when loading a savegame 

### ISSUE THREAD

**Issue by Octavio1994** [JuniorDjjr/CLEOPlus#6]
Hello again my friend! I finally identified the issue I couldn't show you the last time,

Sometimes when using a cleo+ script like vehicle attach, and after playing a savegame and load another one the game crashes.

Here is my log... 

Game version: GTA SA 1.0 US
Unhandled exception at 0x76FC138C in ntdll.dll (+0x4138c): 0xC0000005: Access violation writing location 0x112DBE20.
    Register dump:
        EAX: 0x36FF86F9  EBX: 0x112DBE28  ECX: 0x00D60000  EDX: 0x00000003  
        EDI: 0x00D60000  ESI: 0x112DBE20  EBP: 0x0028DC5C  EIP: 0x76FC138C  
        ESP: 0x0028DC20  EFL: 0x00010206  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0028DC20:  00D60000 00CB3C98 00D6012C 76FBF3B0 00D60000 00000000
        0x0028DC38:  04010888 00000000 0D090400 00EBB880 70909680 5148423B
        0x0028DC50:  02A80011 00000000 7091234D 0028DD54 76FA4D1F 04010888
        0x0028DC68:  04010888 00000800 00000000 77BFD0D7 00000000 00D60000
        0x0028DC80:  04010890 00EDEE40 00D61340 1AFD6E00 00000148 00D60000
        0x0028DC98:  00800000 00EDE3C8 0028DD90 76FA3941 00D60000 00D63C30
        0x0028DCB0:  77BFD013 00000000 00D60000 00EDED70 0028DCE0 76FC9AF1
        0x0028DCC8:  00EBB880 00000000 00000010 00000003 00EFBB48 00000000
        0x0028DCE0:  00D60000 040A3C20 00D60150 0000000E 002F0048 00000000
        0x0028DCF8:  00D60000 04028868 80000181 040A3258 00000000 00000000
        base: 0x00090000   top: 0x0028DC20   bottom: 0x00290000
        
    Backtrace (may be wrong):
        =>0x76FC138C RtlDosPathNameToNtPathName_U_WithStatus+0x6e0 in ntdll.dll (+0x4138c) (0x0028DC5C) 
          0x76FA4D1F RtlInitializeCriticalSection+0x11f in ntdll.dll (+0x24d1f) (0x0028DD54) 
          0x76FA3515 RtlQueryPerformanceCounter+0x281 in ntdll.dll (+0x23515) (0x0028DD74) 
          0x76FBFB0B _allmul+0x48b in ntdll.dll (+0x3fb0b) (0x0028DDC4) 
          0x76FA8083 LdrUnlockLoaderLock+0x7b1 in ntdll.dll (+0x28083) (0x0028DE00) 
          0x76F9E9E3 RtlFreeHeap+0x7e in ntdll.dll (+0x1e9e3) (0x0028DE18) 
          0x757914BD HeapFree+0x14 in kernel32.dll (+0x114bd) (0x0028DE2C) 
          0x717213C7 GetPluginData+0x3f187 in modloader.asi (+0x613c7) (0x0028DE40) 
          0x7170CCB5 GetPluginData+0x2aa75 in modloader.asi (+0x4ccb5) (0x0028DE58) 
          0x716E0A2A in modloader.asi (+0x20a2a) (0x0028DE7C) 
          0x716E10DD in modloader.asi (+0x210dd) (0x0028DE90) 
          0x716E5EE0 GetPluginData+0x3ca0 in modloader.asi (+0x25ee0) (0x0028DEB0) 
          0x716E5BA5 GetPluginData+0x3965 in modloader.asi (+0x25ba5) (0x0028DFF0) 
          0x716DEE28 in modloader.asi (+0x1ee28) (0x0028E00C) 
          0x716DE1AC in modloader.asi (+0x1e1ac) (0x0028E094) 
          0x716DB3CD in modloader.asi (+0x1b3cd) (0x0028E0A0) 
          0x716C949B in modloader.asi (+0x949b) (0x0028E0B4) 
          0x757D03CB GetProfileStringW+0x12def in kernel32.dll (+0x503cb) (0x0028E13C) 
          0x0082D885 in gta_sa.exe (+0x42d885) (0x0028E158)

**Comment by JuniorDjjr** [comment]
Weird, in the backtrace there is only modloader related stuff, ntdll is just problem release, it started from modloader, nothing about CLEO+ or scripts.  But I'm not dismissing the possibility.
Also, CLEO+ does nothing about vehicle attach iirc.

**Comment by Octavio1994** [comment]
thank you for quick reply! I will try to check out more stuff and retrieve additional info if possible!

**Comment by Octavio1994** [comment]
Happy new year my friend! 

After further checking I noticed that when adding new mods to the game it's not a good practice either:

-Creating too many folders inside modloader
-Putting too many files in a single folder

I have the vanilla game zipped and other zip with a bunch of mods (cleo 4.1 by default) so i unzip vanilla first and then unzip mods

If I start and play at least one time with cleo 4.1 and then close game and update to 4.4 with cleo+ I never have issues at all. 

But If I directly unzip cleo 4.4 and cleo+ strange messages appear when I exit the game. Anyways, I recently started to use mixsets and don't know why i didn't try it before :) Mixsets is a real jewel among mods, I love the option "SkipShutdown" 

My best wishes for this year!

**Comment by JuniorDjjr** [comment]
But which crashes were they? Just mentioning that a crash happened doesn't help, it could have been anything, mod conflicts, etc.

**Comment by Octavio1994** [comment]
I understand very well what you mean, BUT the problem here is:

-The crashes are not punctual or recurrent.

-They randomly happen under random circumstances, sometimes while playing sometimes while loading a game.

-They happen very few times, but they do happen!

So to whow you again the issue, I played for like an hour and got this crash while using cleo 4.4 and cleo+. 

The log blames Limit.Adjuster **BUT WEIRDLY THIS ONLY HAPPEN ON CLEO 4.4** 

I NEVER GET SUCH CRASHES ON CLEO 4.1

--When i erased all mods but cleo 4.4 and cleo+ i got the first log i showed you first--.

Game version: GTA SA 1.0 US
Unhandled exception at 0x742D39C0 in III.VC.SA.LimitAdjuster.asi (+0x339c0): 0xC0000005: Access violation reading location 0xFF4C54B3.
    Register dump:
        EAX: 0x010EB0C4  EBX: 0xFF4C545F  ECX: 0x000001F0  EDX: 0x44147432  
        EDI: 0x129E3AD8  ESI: 0x00C4B848  EBP: 0x00000003  EIP: 0x742D39C0  
        ESP: 0x0028F13C  EFL: 0x00010286  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0028F13C:  0028F2B0 010EB0FD 129E3AD8 00000000 00004ECE 3F360000
        0x0028F154:  C1815480 C08551FF 3FC6F3FC 4158DE80 44147488 3FC9A940
        0x0028F16C:  00000004 0000003E 0000000E 00000000 0000004B 00000010
        0x0028F184:  00001000 C0930001 000001F0 C0E80000 40AE8000 3F360000
        0x0028F19C:  C092C000 40D0C000 3F360000 C0930000 40C74000 3F360000
        0x0028F1B4:  00000000 00000000 44D35556 0070A611 129E3AD8 45035317
        0x0028F1CC:  44D297BD 45041317 44D417BD 0028F2B0 40C00001 00000000
        0x0028F1E4:  00000000 C0C00001 00000000 00000000 00000000 00000000
        0x0028F1FC:  41700000 3F800000 010EB0C4 010EB0FD 00000000 00000066
        0x0028F214:  00000200 010EB0C4 010EB0FD 4502B802 44D35556 4505F392
        base: 0x00090000   top: 0x0028F13C   bottom: 0x00290000
        
    Backtrace (may be wrong):
        =>0x742D39C0 in III.VC.SA.LimitAdjuster.asi (+0x339c0) (0x0028F1BC) 
          0x0070A611 in gta_sa.exe (+0x30a611) (0x0028F22C) 
          0x0070B9C7 in gta_sa.exe (+0x30b9c7) (0x0028F2B8) 
          0x0070BC31 in gta_sa.exe (+0x30bc31) (0x0028F2D0) 
          0x006FD431 in gta_sa.exe (+0x2fd431) (0x0028F360) 
          0x00455932 in gta_sa.exe (+0x55932)

**Comment by Octavio1994** [comment]
Adittionally, I believe this could be rather a cleo 4.4 issue, I checked in some forums and  Im not the only one having issues with cleo+

**Comment by JuniorDjjr** [comment]
Open Limit Adjuster error, not related to CLEO+, send in OLA github.
btw I use OLA, CLEO 4.4 and CLEO+, all latest version, 100% of the times in my game, no problems here.

**Comment by Octavio1994** [comment]
thank you! will check out OLA from mixsets!

**Comment by Octavio1994** [comment]
sadly still got a crash again today :( 

Game version: GTA SA 1.0 US
Unhandled exception at 0x775CE9A4 in ntdll.dll (+0x1e9a4): 0xC0000005: Access violation reading location 0x1AB5606F.
    Register dump:
        EAX: 0x1AB56068  EBX: 0x1AB56070  ECX: 0x1AA626F0  EDX: 0x00A8B42C  
        EDI: 0x00000000  ESI: 0x00CC0000  EBP: 0x0028F4A8  EIP: 0x775CE9A4  
        ESP: 0x0028F498  EFL: 0x00010246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0028F498:  1ACC5E08 1AA626F0 00D1B908 00000000 0028F4BC 752714BD
        0x0028F4B0:  00CC0000 00000000 1AB56070 0028F4D0 73C2716E 00CC0000
        0x0028F4C8:  00000000 1AB56070 0028F4E0 73C1B125 1AB56070 00000000
        0x0028F4E0:  0028F508 73C10DED 1AB56070 4B7C2E59 1AA626F0 1ACC5E08
        0x0028F4F8:  00D1B908 0028F578 73C3A0A0 FFFFFFFF 0028F528 73C105F5
        0x0028F510:  00D3B520 00D3B520 00D3B5F4 73C7415C 0028F530 4B7C2E79
        0x0028F528:  0028F530 73C0E7A2 0028F584 735EFC97 4B75A9E1 0028F58C
        0x0028F540:  0028F5F0 00D3B5F0 00000000 00000000 0028F540 00825EA4
        0x0028F558:  0028F5A4 00000014 00000000 008E2C90 0028F574 0082AD25
        0x0028F570:  01081EA8 0028F5B4 0028F5DC 736389AD 00000000 0028F5C4
        base: 0x00090000   top: 0x0028F498   bottom: 0x00290000
        
    Backtrace (may be wrong):
        =>0x775CE9A4 RtlFreeHeap+0x3f in ntdll.dll (+0x1e9a4) (0x0028F4A8) 
          0x752714BD HeapFree+0x14 in kernel32.dll (+0x114bd) (0x0028F4BC) 
          0x73C2716E CLEO_GetVersion+0x1984e in CLEO.asi (+0x2716e) (0x0028F4D0) 
          0x73C1B125 CLEO_GetVersion+0xd805 in CLEO.asi (+0x1b125) (0x0028F4E0) 
          0x73C10DED CLEO_GetVersion+0x34cd in CLEO.asi (+0x10ded) (0x0028F508) 
          0x73C105F5 CLEO_GetVersion+0x2cd5 in CLEO.asi (+0x105f5) (0x0028F528) 
          0x73C0E7A2 CLEO_GetVersion+0xe82 in CLEO.asi (+0xe7a2) (0x0028F530) 
          0x735EFC97 in MixSets.asi (+0xfc97) (0x0028F584) 
          0x735F2BF5 in MixSets.asi (+0x12bf5) (0x0028F5C4) 
          0x735F13FB in MixSets.asi (+0x113fb) (0x0028F5E8) 
          0x735FDBFE in MixSets.asi (+0x1dbfe) (0x0028F6E8) 
          0x0053BDDC in gta_sa.exe (+0x13bddc) (0x0028F74C) 
          0x73B6AD2C GetCleoPlusVersion+0x1706c in CLEO+.cleo (+0x2ad2c) (0x0028F784) 
          0x73B6207B GetCleoPlusVersion+0xe3bb in CLEO+.cleo (+0x2207b) (0x0028F7A8) 
          0x73B5DE58 GetCleoPlusVersion+0xa198 in CLEO+.cleo (+0x1de58) (0x0028F8A8) 
          0x0053C6E0 in gta_sa.exe (+0x13c6e0) (0x0028F8B8) 
          0x00748E0E in gta_sa.exe (+0x348e0e) (0x0028F950) 
          0x7386FB94 in modloader.asi (+0x1fb94) (0x0028F970) 
          0x7386DE46 in modloader.asi (+0x1de46) (0x0028F9A0)

**Comment by Octavio1994** [comment]
while loading another saved game from the menu...

**Comment by Octavio1994** [comment]
maybe did you optimize cleo+ for win10 or something?

**Comment by JuniorDjjr** [comment]
After CLEO+, it runs gta_sa.exe, then MixSets, then CLEO. It is very far from having anything to do with CLEO+.

From the beginning you are here asking for help with a problem that is unrelated to CLEO+.

Just follows the instructions in [CrashInfo](https://www.mixmods.com.br/2022/09/crashinfo/).
