### ISSUE TITLE
0E33: GET_PICKUP_THIS_COORD can break 0214: HAS_PICKUP_BEEN_COLLECTED

### ISSUE THREAD

**Issue by OrionSR** [JuniorDjjr/CLEOPlus#8]
There are two issues related to 0E33: get_pickup_this_coord
- If the Only_Available param is True, then the `if (!onlyAvailable || !CPickups::IsPickUpPickedUp(pickupRef))` check can prevent a collected pickup from being detected as picked up again by the script that "owns" the pickup. When a pickup is detected as collected by opcode 0214, it's handle is cleared from the CollectedPickups array so it won't be detected as collected again - unless it respawns and is collected again. Save disks can be picked up but won't show the save screen. Property is payed for but the mini-mission won't unlock the property.
- I suspect that the purpose of the Only_Available param is to filter out pickups that have been permanently collected, deleted, or never used so that only valid pickup handles are returned. Checking the type of the pickup might provide a better test as any pickup that is not type 0 is a valid pickup. 

More information and a cleo repro script can be provided if needed. I suspect that you'll figure it out quickly enough. Seemann and I argued out the logic of the issue in the Sanny Discord server's #sdk-and-plugins channel. This discussion may provide additional details and context.
https://discordapp.com/channels/911487285990674473/938823120242999326/1106000841841848392

**Comment by JuniorDjjr** [comment]
I use this on Buy Property Mod and works, or maybe my case is not influenced by this issue, I don't know, I don't remember how I used this and I have no idea when I will be able to verify this issue.

**Comment by OrionSR** [comment]
It could be that I misunderstood the purpose of the Only_Available parameter, that the opcode is functioning properly and won't cause any issues when used as intended, and that existing scripts might break if changes are made to the filter. Clarifying the purpose of the opcode might be the best option for avoiding conflicts - a warning against using the Only_Available option on any pickup not owned by the script.

I am in no rush for any changes, if necessary. I wrote a custom function modeled on 0E33, but it includes a search radius, and can continue the search after the previous handle. While testing this function I discovered that I could break the collection detection of standard and custom scripts if I intentionally used 0E33 incorrectly.

**Comment by x87** [comment]
@OrionSR can you test 0E33 with this version. I replaced CPickups::IsPickUpPickedUp with the type check
[CLEO+.zip](https://github.com/JuniorDjjr/CLEOPlus/files/11470836/CLEO%2B.zip)

**Comment by OrionSR** [comment]
The updated Cleo+ linked above passed two types of tests with no issues.

1. _Does 0E33 still break 0214's collection detection?_ **No.** The repro script I designed to force glitches with the collection of save disks, buy properties, and custom pickups did not encounter any errors with the linked Cleo+.

2. _Does 0E33 return the appropriate pickup handles?_ **Yes.**   Five identical pickups were created in the same location. The 1st, 2nd, and 5th pickup were immediately destroyed. 0E33 returned the handle of the 1st pickup when Only_Available == 0. 0E33 returned the handle of the 3rd pickup when Only_Available == 1. 
 
These results match my expectations for 0E33 using a pickup Type check.

Technicalities: These tests were conducted on a baseline save with a pristine pickup pool. Normally new pickups fill the first free slot, but it is possible for the 5th pickup created in sequence to have a lower index than the 1st pickup. When no pickup slots are free, the game will start recycling dropped pickups that are waiting to expire the next time the player is near.
